version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: 58-hack-api
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: [ "air", "-c", "air.toml" ]