FROM golang:1.24.2-alpine AS base

RUN apk add --no-cache git

WORKDIR /tmp/echo

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY . .

ENV GOOS=linux
ENV GOARCH=amd64
RUN go build -o bootstrap ./cmd/main.go

FROM alpine:3.9

RUN apk add ca-certificates

COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.9.0 /lambda-adapter /opt/extensions/lambda-adapter

COPY --from=base /tmp/echo/bootstrap /app/bootstrap

ENV PORT=8080 
EXPOSE 8080

CMD ["/app/bootstrap"]
